### LAB Item 1

1. Run weather regression from 1/1/2012 --> 8/1/2019 to Natural Gas Consumption.  Use the data posted in week 7 folder.

    https://www.eia.gov/dnav/ng/ng_cons_sum_dcu_nus_m.htm   (original source but use data in class folder)
    
2. Using SkLearn, regress to sum of: U.S. Natural Gas Residential Consumption (MMcf) + Natural Gas Deliveries to Commercial Consumers (Including Vehicle Fuel through 1996) in the U.S. (MMcf)

3. What is R^2 ?

4. Estimate October 2019!  What was the residual between your estimate and the actual.

In [3]:
import numpy
import pandas
import sklearn
from matplotlib import pyplot as plt
%matplotlib inline

import plotly
#import chart_studio.plotly as py
import cufflinks

import plotly.graph_objects as go
#from chart_studio.plotly import plot, iplot

In [4]:
temp_df = pandas.read_excel(r"C:\\Users\khalil\ML Lab 7\weather-natgas.xlsx" , sheet_name='Weather')

In [5]:
ng_df  = pandas.read_excel(r"C:\\Users\khalil\ML Lab 7\weather-natgas.xlsx" , sheet_name='NatGas')

In [6]:
temp_df.head()

    themonth        hdd       cdd  temp_natl
0 2017-01-01  23.648603  0.313590  41.664987
1 2017-02-01  18.392368  0.537725  47.145357
2 2017-03-01  16.762865  0.893394  49.130529
3 2017-04-01   7.544863  2.058533  59.513670
4 2017-05-01   4.333481  3.636984  64.303503

In [7]:
ng_df.tail()

,Date,U.S. Natural Gas Total Consumption (MMcf),U.S. Natural Gas Lease and Plant Fuel Consumption (MMcf),U.S. Natural Gas Pipeline & Distribution Use (MMcf),Natural Gas Delivered to Consumers in the U.S. (MMcf),U.S. Natural Gas Residential Consumption (MMcf),Natural Gas Deliveries to Commercial Consumers (Including Vehicle Fuel through 1996) in the U.S. (MMcf),U.S. Natural Gas Industrial Consumption (MMcf),U.S. Natural Gas Vehicle Fuel Consumption (MMcf),U.S. Natural Gas Deliveries to Electric Power Consumers (MMcf)
29,2019-06-01,2119341,147863,68482,1902995,129214,144653,634196,4370,990562
30,2019-07-01,2393904,153635,77819,2162450,111761,141950,649556,4515,1254667
31,2019-08-01,2433924,157370,79079,2197474,101894,140788,672373,4515,1277904
32,2019-09-01,2206252,152877,71327,1982049,109841,143158,643905,4370,1080775
33,2019-10-01,2306544,159359,74586,2072599,231696,216141,683580,4515,936668

In [8]:
#Q 1
temp_df['themonth'] = pandas.to_datetime(temp_df['themonth'])
ng_df['Date'] = pandas.to_datetime(ng_df['Date'])

In [9]:
m_df = temp_df.merge(ng_df, left_on=['themonth'], right_on=['Date'])
m_df['ones'] = 1
m_df.tail()

,themonth,hdd,cdd,temp_natl,Date,U.S. Natural Gas Total Consumption (MMcf),U.S. Natural Gas Lease and Plant Fuel Consumption (MMcf),U.S. Natural Gas Pipeline & Distribution Use (MMcf),Natural Gas Delivered to Consumers in the U.S. (MMcf),U.S. Natural Gas Residential Consumption (MMcf),Natural Gas Deliveries to Commercial Consumers (Including Vehicle Fuel through 1996) in the U.S. (MMcf),U.S. Natural Gas Industrial Consumption (MMcf),U.S. Natural Gas Vehicle Fuel Consumption (MMcf),U.S. Natural Gas Deliveries to Electric Power Consumers (MMcf),ones
29,2019-06-01,0.668620,7.894777,72.226157,2019-06-01,2119341,147863,68482,1902995,129214,144653,634196,4370,990562,1
30,2019-07-01,0.041155,12.464210,77.423055,2019-07-01,2393904,153635,77819,2162450,111761,141950,649556,4515,1254667,1
31,2019-08-01,0.081061,11.162419,76.081358,2019-08-01,2433924,157370,79079,2197474,101894,140788,672373,4515,1277904,1
32,2019-09-01,0.916233,8.597273,72.681040,2019-09-01,2206252,152877,71327,1982049,109841,143158,643905,4370,1080775,1
33,2019-10-01,7.809861,2.738358,59.928497,2019-10-01,2306544,159359,74586,2072599,231696,216141,683580,4515,936668,1

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
reg = LinearRegression().fit(m_df[['temp_natl']], m_df[['U.S. Natural Gas Residential Consumption (MMcf)']])

In [12]:
reg_pred = reg.predict(m_df[['temp_natl']])

In [13]:
 reg_pred

array([[747301.84536559],
       [633923.42721053],
       [592854.00184443],
       [378046.59130379],
       [278954.06474044],
       [103374.19714355],
       [ 19077.88536711],
       [ 68321.49182395],
       [153367.32439739],
       [331123.03461784],
       [567732.63450156],
       [789686.9477938 ],
       [842172.31205872],
       [690456.08603829],
       [640624.48243962],
       [504892.20002534],
       [188766.31506553],
       [ 84719.53467095],
       [  9170.22302468],
       [ 27304.27291418],
       [125760.30241701],
       [373801.70779288],
       [648919.75467068],
       [731754.80843373],
       [827197.66801059],
       [763260.89239024],
       [656009.01771917],
       [412463.78947712],
       [263690.12103614],
       [115049.45480311],
       [  7535.5298118 ],
       [ 35292.68062875],
       [105638.78502264],
       [369464.61543885]])

In [14]:
reg.score(m_df[['temp_natl']], m_df[['U.S. Natural Gas Residential Consumption (MMcf)']])

0.9356485366095912

In [15]:
#Q 2
m_df['rescomm'] = m_df['Natural Gas Deliveries to Commercial Consumers (Including Vehicle Fuel through 1996) in the U.S. (MMcf)'] + m_df['U.S. Natural Gas Residential Consumption (MMcf)']

In [16]:
m_df.tail()

,themonth,hdd,cdd,temp_natl,Date,U.S. Natural Gas Total Consumption (MMcf),U.S. Natural Gas Lease and Plant Fuel Consumption (MMcf),U.S. Natural Gas Pipeline & Distribution Use (MMcf),Natural Gas Delivered to Consumers in the U.S. (MMcf),U.S. Natural Gas Residential Consumption (MMcf),Natural Gas Deliveries to Commercial Consumers (Including Vehicle Fuel through 1996) in the U.S. (MMcf),U.S. Natural Gas Industrial Consumption (MMcf),U.S. Natural Gas Vehicle Fuel Consumption (MMcf),U.S. Natural Gas Deliveries to Electric Power Consumers (MMcf),ones,rescomm
29,2019-06-01,0.668620,7.894777,72.226157,2019-06-01,2119341,147863,68482,1902995,129214,144653,634196,4370,990562,1,273867
30,2019-07-01,0.041155,12.464210,77.423055,2019-07-01,2393904,153635,77819,2162450,111761,141950,649556,4515,1254667,1,253711
31,2019-08-01,0.081061,11.162419,76.081358,2019-08-01,2433924,157370,79079,2197474,101894,140788,672373,4515,1277904,1,242682
32,2019-09-01,0.916233,8.597273,72.681040,2019-09-01,2206252,152877,71327,1982049,109841,143158,643905,4370,1080775,1,252999
33,2019-10-01,7.809861,2.738358,59.928497,2019-10-01,2306544,159359,74586,2072599,231696,216141,683580,4515,936668,1,447837

In [17]:
#Q 3
m_df['temp_natl_sq'] = m_df['temp_natl'] **2 #square temperature

In [18]:
reg1 = LinearRegression().fit(m_df[['temp_natl']], m_df[['rescomm']])

In [19]:
reg_pred = reg.predict(m_df[['temp_natl']])

In [20]:
reg_pred

array([[747301.84536559],
       [633923.42721053],
       [592854.00184443],
       [378046.59130379],
       [278954.06474044],
       [103374.19714355],
       [ 19077.88536711],
       [ 68321.49182395],
       [153367.32439739],
       [331123.03461784],
       [567732.63450156],
       [789686.9477938 ],
       [842172.31205872],
       [690456.08603829],
       [640624.48243962],
       [504892.20002534],
       [188766.31506553],
       [ 84719.53467095],
       [  9170.22302468],
       [ 27304.27291418],
       [125760.30241701],
       [373801.70779288],
       [648919.75467068],
       [731754.80843373],
       [827197.66801059],
       [763260.89239024],
       [656009.01771917],
       [412463.78947712],
       [263690.12103614],
       [115049.45480311],
       [  7535.5298118 ],
       [ 35292.68062875],
       [105638.78502264],
       [369464.61543885]])

In [21]:
reg.score(m_df[['temp_natl']], m_df[['rescomm']])

0.43281248829561114

In [22]:
#Q 4
temp_df = pandas.read_excel(r"C:\\Users\khalil\ML Lab 7\weather-natgas.xlsx" , sheet_name='Weather')

In [23]:
ng_df  = pandas.read_excel(r"C:\\Users\khalil\ML Lab 7\weather-natgas.xlsx" , sheet_name='NatGas')

In [24]:
temp_df.tail()

     themonth        hdd        cdd  temp_natl
30 2019-07-01   0.041155  12.464210  77.423055
31 2019-08-01   0.081061  11.162419  76.081358
32 2019-09-01   0.916233   8.597273  72.681040
33 2019-10-01   7.809861   2.738358  59.928497
34 2019-11-01  18.480750   0.573533  47.092783

In [25]:
ng_df.tail()

,Date,U.S. Natural Gas Total Consumption (MMcf),U.S. Natural Gas Lease and Plant Fuel Consumption (MMcf),U.S. Natural Gas Pipeline & Distribution Use (MMcf),Natural Gas Delivered to Consumers in the U.S. (MMcf),U.S. Natural Gas Residential Consumption (MMcf),Natural Gas Deliveries to Commercial Consumers (Including Vehicle Fuel through 1996) in the U.S. (MMcf),U.S. Natural Gas Industrial Consumption (MMcf),U.S. Natural Gas Vehicle Fuel Consumption (MMcf),U.S. Natural Gas Deliveries to Electric Power Consumers (MMcf)
29,2019-06-01,2119341,147863,68482,1902995,129214,144653,634196,4370,990562
30,2019-07-01,2393904,153635,77819,2162450,111761,141950,649556,4515,1254667
31,2019-08-01,2433924,157370,79079,2197474,101894,140788,672373,4515,1277904
32,2019-09-01,2206252,152877,71327,1982049,109841,143158,643905,4370,1080775
33,2019-10-01,2306544,159359,74586,2072599,231696,216141,683580,4515,936668

In [26]:
temp_df['themonth'] = pandas.to_datetime(temp_df['themonth'])
ng_df['Date'] = pandas.to_datetime(ng_df['Date'])

In [27]:
m_df = temp_df.merge(ng_df, left_on=['themonth'], right_on=['Date'])
m_df['ones'] = 1
m_df.tail()

,themonth,hdd,cdd,temp_natl,Date,U.S. Natural Gas Total Consumption (MMcf),U.S. Natural Gas Lease and Plant Fuel Consumption (MMcf),U.S. Natural Gas Pipeline & Distribution Use (MMcf),Natural Gas Delivered to Consumers in the U.S. (MMcf),U.S. Natural Gas Residential Consumption (MMcf),Natural Gas Deliveries to Commercial Consumers (Including Vehicle Fuel through 1996) in the U.S. (MMcf),U.S. Natural Gas Industrial Consumption (MMcf),U.S. Natural Gas Vehicle Fuel Consumption (MMcf),U.S. Natural Gas Deliveries to Electric Power Consumers (MMcf),ones
29,2019-06-01,0.668620,7.894777,72.226157,2019-06-01,2119341,147863,68482,1902995,129214,144653,634196,4370,990562,1
30,2019-07-01,0.041155,12.464210,77.423055,2019-07-01,2393904,153635,77819,2162450,111761,141950,649556,4515,1254667,1
31,2019-08-01,0.081061,11.162419,76.081358,2019-08-01,2433924,157370,79079,2197474,101894,140788,672373,4515,1277904,1
32,2019-09-01,0.916233,8.597273,72.681040,2019-09-01,2206252,152877,71327,1982049,109841,143158,643905,4370,1080775,1
33,2019-10-01,7.809861,2.738358,59.928497,2019-10-01,2306544,159359,74586,2072599,231696,216141,683580,4515,936668,1

In [28]:
reg = LinearRegression().fit(m_df[['temp_natl']], m_df[['U.S. Natural Gas Residential Consumption (MMcf)']])

In [29]:
reg_pred2 = reg.predict(m_df[['temp_natl']])

In [30]:
# reg_pred

In [31]:
reg.score(m_df[['temp_natl']], m_df[['U.S. Natural Gas Residential Consumption (MMcf)']])

0.9356485366095912

### LAB Item 2

1. Run the same calculation as LAB Item 1 using the python statsmodels package

import statsmodels.api as sm

mod = sm.OLS(Y, X)

res = mod.fit()

In [60]:
import statsmodels.formula.api as smf
import numpy as np

In [70]:
# Q 1
df = pd.DataFrame(m_df) 

x = df[['temp_natl','U.S. Natural Gas Residential Consumption (MMcf)']]
y = df['temp_natl']

x = sm.add_constant(x)

model = sm.OLS(y, x).fit()
predictions = model.predict(x) 

print_model = model.summary()
print(print_model)

                            OLS Regression Results
==============================================================================
Dep. Variable:              temp_natl   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 3.292e+23
Date:                Thu, 02 Mar 2023   Prob (F-statistic):               0.00
Time:                        09:56:05   Log-Likelihood:                 736.96
No. Observations:                  34   AIC:                            -1468.
Df Residuals:                      31   BIC:                            -1463.
Df Model:                           2
Covariance Type:            nonrobust
===================================================================================================================
                                                      coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------------------------
const                                           -2.489e-10   3.73e-10     -0.667      0.510   -1.01e-09    5.12e-10
temp_natl                                           1.0000   4.86e-12   2.06e+11      0.000       1.000       1.000
U.S. Natural Gas Residential Consumption (MMcf) -2.536e-17   2.27e-16     -0.112      0.912   -4.89e-16    4.38e-16
==============================================================================
Omnibus:                       16.579   Durbin-Watson:                   0.078
Prob(Omnibus):                  0.000   Jarque-Bera (JB):                3.207
Skew:                           0.211   Prob(JB):                        0.201
Kurtosis:                       1.556   Cond. No.                     1.07e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.07e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

C:\Users\khalil\anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning:

In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only

In [80]:
# Q 2
m_df['rescomm'] = m_df['Natural Gas Deliveries to Commercial Consumers (Including Vehicle Fuel through 1996) in the U.S. (MMcf)'] + m_df['U.S. Natural Gas Residential Consumption (MMcf)']

In [81]:
m_df['temp_natl_sq'] = m_df['temp_natl'] **2 #square temperature

In [82]:
df1 = pd.DataFrame(m_df) 

x = df1[['temp_natl','rescomm']]
y = df1['temp_natl']

x = sm.add_constant(x)

model = sm.OLS(y, x).fit()
predictions = model.predict(x) 

print_model = model.summary()
print(print_model)

                            OLS Regression Results
==============================================================================
Dep. Variable:              temp_natl   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 6.472e+23
Date:                Thu, 02 Mar 2023   Prob (F-statistic):               0.00
Time:                        10:10:19   Log-Likelihood:                 748.45
No. Observations:                  34   AIC:                            -1491.
Df Residuals:                      31   BIC:                            -1486.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.035e-10   2.83e-10     -0.366      0.717    -6.8e-10    4.73e-10
temp_natl      1.0000   3.55e-12   2.81e+11      0.000       1.000       1.000
rescomm    -1.209e-17   1.12e-16     -0.108      0.915   -2.41e-16    2.17e-16
==============================================================================
Omnibus:                       17.057   Durbin-Watson:                   0.119
Prob(Omnibus):                  0.000   Jarque-Bera (JB):                3.202
Skew:                           0.194   Prob(JB):                        0.202
Kurtosis:                       1.547   Cond. No.                     1.86e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.86e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

C:\Users\khalil\anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning:

In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only

In [75]:
# Q 3
import statsmodels.api as sm
model = sm.OLS(m_df[['U.S. Natural Gas Residential Consumption (MMcf)']], m_df[['temp_natl', 'ones']])
results = model.fit()
results.params

temp_natl   -2.068810e+04
ones         1.609271e+06
dtype: float64

In [76]:
print(results.summary())

                                           OLS Regression Results
===========================================================================================================
Dep. Variable:     U.S. Natural Gas Residential Consumption (MMcf)   R-squared:                       0.936
Model:                                                         OLS   Adj. R-squared:                  0.934
Method:                                              Least Squares   F-statistic:                     465.3
Date:                                             Wed, 01 Mar 2023   Prob (F-statistic):           1.25e-20
Time:                                                     20:35:32   Log-Likelihood:                -429.37
No. Observations:                                               34   AIC:                             862.7
Df Residuals:                                                   32   BIC:                             865.8
Df Model:                                                        1
Covariance Type:                                         nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
temp_natl  -2.069e+04    959.110    -21.570      0.000   -2.26e+04   -1.87e+04
ones        1.609e+06   5.82e+04     27.630      0.000    1.49e+06    1.73e+06
==============================================================================
Omnibus:                        1.824   Durbin-Watson:                   1.201
Prob(Omnibus):                  0.402   Jarque-Bera (JB):                1.135
Skew:                          -0.079   Prob(JB):                        0.567
Kurtosis:                       2.119   Cond. No.                         271.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [76]:
# Q 4
temp_df = pandas.read_excel(r"C:\\Users\khalil\ML Lab 7\weather-natgas.xlsx" , sheet_name='Weather')
ng_df  = pandas.read_excel(r"C:\\Users\khalil\ML Lab 7\weather-natgas.xlsx" , sheet_name='NatGas')

In [77]:
temp_df['themonth'] = pandas.to_datetime(temp_df['themonth'])
ng_df['Date'] = pandas.to_datetime(ng_df['Date'])

In [84]:
m_df1 = temp_df.merge(ng_df, left_on=['themonth'], right_on=['Date'])
m_df1['ones'] = 1
m_df1.tail()

,themonth,hdd,cdd,temp_natl,Date,U.S. Natural Gas Total Consumption (MMcf),U.S. Natural Gas Lease and Plant Fuel Consumption (MMcf),U.S. Natural Gas Pipeline & Distribution Use (MMcf),Natural Gas Delivered to Consumers in the U.S. (MMcf),U.S. Natural Gas Residential Consumption (MMcf),Natural Gas Deliveries to Commercial Consumers (Including Vehicle Fuel through 1996) in the U.S. (MMcf),U.S. Natural Gas Industrial Consumption (MMcf),U.S. Natural Gas Vehicle Fuel Consumption (MMcf),U.S. Natural Gas Deliveries to Electric Power Consumers (MMcf),ones
29,2019-06-01,0.668620,7.894777,72.226157,2019-06-01,2119341,147863,68482,1902995,129214,144653,634196,4370,990562,1
30,2019-07-01,0.041155,12.464210,77.423055,2019-07-01,2393904,153635,77819,2162450,111761,141950,649556,4515,1254667,1
31,2019-08-01,0.081061,11.162419,76.081358,2019-08-01,2433924,157370,79079,2197474,101894,140788,672373,4515,1277904,1
32,2019-09-01,0.916233,8.597273,72.681040,2019-09-01,2206252,152877,71327,1982049,109841,143158,643905,4370,1080775,1
33,2019-10-01,7.809861,2.738358,59.928497,2019-10-01,2306544,159359,74586,2072599,231696,216141,683580,4515,936668,1

In [85]:
df2 = pd.DataFrame(m_df1) 

x = df[['temp_natl','rescomm']]
y = df['temp_natl']

x = sm.add_constant(x)

model = sm.OLS(y, x).fit()
predictions = model.predict(x) 

print_model = model.summary()
print(print_model)

                            OLS Regression Results
==============================================================================
Dep. Variable:              temp_natl   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 6.472e+23
Date:                Thu, 02 Mar 2023   Prob (F-statistic):               0.00
Time:                        10:10:50   Log-Likelihood:                 748.45
No. Observations:                  34   AIC:                            -1491.
Df Residuals:                      31   BIC:                            -1486.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.035e-10   2.83e-10     -0.366      0.717    -6.8e-10    4.73e-10
temp_natl      1.0000   3.55e-12   2.81e+11      0.000       1.000       1.000
rescomm    -1.209e-17   1.12e-16     -0.108      0.915   -2.41e-16    2.17e-16
==============================================================================
Omnibus:                       17.057   Durbin-Watson:                   0.119
Prob(Omnibus):                  0.000   Jarque-Bera (JB):                3.202
Skew:                           0.194   Prob(JB):                        0.202
Kurtosis:                       1.547   Cond. No.                     1.86e+07
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.86e+07. This might indicate that there are
strong multicollinearity or other numerical problems.

C:\Users\khalil\anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning:

In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only

### LAB Item 3

Return to previous dataset: Adult income
https://www.kaggle.com/wenruliu/adult-income-dataset

Build a logistic Regression targeting income above / below 50k...

Review Example.

In [90]:
import postgresql
import pandas as pd

In [91]:
df = pandas.read_csv(r'C:\Users\khalil\ML Lab 7\adult.csv')

In [96]:
# Let's use a little Encoding magic.....we'll come back to this later.
for column in df.columns:
    if df[column].dtype == type(object):
        le = sklearn.preprocessing.LabelEncoder()
        df[column] = le.fit_transform(df[column])

In [97]:
x_df = df.drop(columns=['income'])    # We want everything but the response variable...in this case income
y_df = df[['income']]

In [98]:
x_train, x_test, y_train, y_test = train_test_split(x_df, y_df)

In [100]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(random_state=16)
logreg.fit(x_train, y_train)
y_pred = logreg.predict(x_test)

y_pred

C:\Users\khalil\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

array([0, 0, 1, ..., 0, 0, 0])

In [103]:
print('Accuracy: {:.2f}'.format(logreg.score(x_test, y_test)))

Accuracy: 0.80

### LAB Item 4: Let's take a look at the sklearn California housing dataset from previous weeks

... A)  review a multivariate regression from this week's content (built in class notes)

... B) Compare the results from the multivariate linear regression to a random forest by building a RF.  You've built a random forest on this dataset before.  Note the differences in model accuracy between the linear regression and RF.

In [116]:
# B Random Forest
from sklearn.ensemble import RandomForestClassifier

In [117]:
data = pd.read_csv(r'C:\Users\khalil\ML HW 3\housing.csv')
df = pd.DataFrame(data)
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [118]:
df = df.drop('ocean_proximity', axis=1)

In [119]:
df = df.dropna()

In [120]:
x_df = df.drop(columns=['median_house_value'])    
y_df = df[['median_house_value']]

In [121]:
x_train, x_test, y_train, y_test = train_test_split(x_df, y_df)

In [124]:
rf = RandomForestClassifier(n_estimators=5) #100 is no of trees
rf.fit(x_train, y_train)

C:\Users\khalil\AppData\Local\Temp/ipykernel_6748/2074487705.py:2: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

MemoryError: could not allocate 237568000 bytes

In [125]:
pred_df = pd.DataFrame(rf.predict(X_test), columns=['pred'])
pred_df['actual'] = y_test.values
pred_df['residual'] = (pred_df['pred'] - pred_df['actual']).abs()
pred_df

IndexError: list index out of range

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(pred_df['actual'], pred_df['pred'])

Sorry Professor As my system is not able to Allocate much memory and it again and again crashes Python File, thats why I am not able to see and Compare accuracies of Random Forest with Linear Regression